[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flash512-vanguard"
version = "1.0.0"
authors = [
  { name="erabytse", email="support@docudeeper.com" },
]
description = "Advanced Cryptographic Matrix & Phase Mutation Engine"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "Apache-2.0" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Security :: Cryptography",
]

[tool.setuptools.packages.find]
include = ["flash512*"]

[project.urls]
"Homepage" = "https://github.com"
