[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flash512-vanguard"
version = "1.0.0"
authors = [
  { name="erabytse", email="support@docudeeper.com" },
]
description = "Advanced Cryptographic Matrix & Phase Mutation Engine"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Security :: Cryptography",
]

[project.urls]
"Homepage" = "https://github.com"
"Bug Tracker" = "https://github.com/issues"
